id: P010582
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:15:07.410793
source_metadata:
  id: bdr:W8618
  title: ཕར་ཕྱིན་བསམ་འཕེལ་དབང་རྒྱལ་དང་དབུ་མ་ཐར་འདོད་དེད་དཔོན།
  author: ''
  volumes:
    ed2cca0c9775444f84835c3acf75b4de:
      image_group_id: I1KG10844
      title: ''
      volume_number: 1
      total_pages: 1166
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
